name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run TypeScript compilation
      run: npm run build

    - name: Run tests with coverage
      run: npm run test:coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage/lcov.info
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

    - name: Run automated quality assessment
      run: |
        cd tmp/test-example
        npx ts-node automated-test-runner.ts

  quality-gate:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Run quality assessment
      run: |
        cd tmp/test-example
        npx ts-node automated-test-runner.ts > quality-report.txt 2>&1 || true
        cat quality-report.txt

    - name: Check test coverage threshold
      run: |
        COVERAGE=$(npm run test:coverage 2>/dev/null | grep "All files" | tail -1 | awk '{print $NF}' | sed 's/%//')
        if (( $(echo "$COVERAGE < 90" | bc -l) )); then
          echo "❌ Test coverage $COVERAGE% is below 90% threshold"
          exit 1
        else
          echo "✅ Test coverage $COVERAGE% meets 90% threshold"
        fi

    - name: Quality Gate Check
      run: |
        # Check if all tests passed
        if [ $? -eq 0 ]; then
          echo "✅ All quality checks passed!"
        else
          echo "❌ Quality checks failed"
          exit 1
        fi

  deploy:
    runs-on: ubuntu-latest
    needs: [test, quality-gate]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build for production
      run: npm run build

    - name: Create deployment package
      run: |
        mkdir -p dist
        cp package.json dist/
        cp -r src dist/
        cd dist
        npm ci --production

    - name: Deploy to GitHub Pages (optional)
      uses: peaceiris/actions-gh-pages@v4
      if: success()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        cname: feral-code-agent.netlify.app
